var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                           ",
   "  x                                                                                        ",
   "  x                                                                                        ",
   "  x                                                                            x           ",
   "  x        o  o                                                                x           ",
   "  x        xxxx                    o           x     x                         x           ",
   "  x                  xxxx         xxxxx        x!!!!!x     o  o                x           ",
   "  x                                            xxxxxxx     xxxx                x           ",
   "  x                                                                            x           ",
   "  xo                  xxx                                 x                    x           ",
   "  xx                 x  x                             xxxxx                    x           ",
   "  x             xxxxxx  x                                                      x           ",
   "  x             x       x   xxxx                                               x           ",
   "  x          xxxx       x              yyy    xxxxx                            x           ",
   "  x  @  k    x          x                                         xxxxx       ox           ",
   "  xxxxxxxxxxxx          x         xxxxxxxxxxxxxxxxxxxx     xxxxxxx     xxxxxxxxx           ",
   "                        x!!!!!!!!!x                  x     x                               ",
   "                        x!!!!!!!!!x                  x!!!!!x                               ",
   "                        x!!!!!!!!!x                  x!!!!!x                               ",
   "                        xxxxxxxxxxx                  xxxxxxx                               ",
   "                                                                                           ",
   "                                                                                           "],
  ["x                                                                                                                  x",
   "x                                                                                                                  x",
   "x                                                                                                                  x",
   "x        @                                                                                                         x",
   "x      xxxxxx                                                                                                      x",
   "x        v                                                                                                         x",
   "x                                                                                                                  x",
   "x                                                                                                                  x",
   "x x!!!x       x!!x                                                                                                 x",
   "x xxxxx       xxxx                                                                                                 x",
   "x v              v                                                                                                 x",
   "x                                                                                                                  x",
   "x                                                                                                                  x",
   "x                             x           o               o             x                                          x",
   "x                             x            =                            x                                          x",
   "x                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                          x",
   "x                           !!x =                                       x                                          x",
   "x                           !!x                                         x                                          x",
   "x                           !!x           o           o          o      xx                                         x",
   "x    x!!!!x                 !!x       x xxxx xxxxxxx xxxxx xxx xxxx       xx   o     xxxxxx                        x",
   "x    x!!!!x                 !!x       x!!!!!!!!!!!!!!!!!!!!!!!!!!!x          xxxxxxxx           xx                 x",
   "x   xx!!!!xx                !!x      xx!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx                         xxxxx       oooooo   x",
   "x    x!!!!xxx               xxx     xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx                     xxxxxxxxxxxxxxxxxxxxxxxx",
   "x    x!!!!xxx                       xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxx      xxxxxxx                       ",
   "xo  xx!!!!xxxx         =           xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                             v   v                  v                                              "],
  ["x                                                                                                        v   x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x@                                                     v                                                     x",
   "xxxxx                                                                                         v              x",
   "x   v      o     =                                                                                           x",
   "x        xxxxxxxxxx                                                                                          x",
   "x    o        v      =                                                                                       x",
   "x   xxxxx               xxxxx                                                                                x",
   "x                  o        v                                                                                x",
   "x       xxxxxxxxxxxxxxxxx                                                                                    x",
   "x                                   =                o            o                o                       o x",
   "x                           xxxxxxxxxxxxx       xxxxxxxxxxxx   xxxxxxxxxxx   xxxxxxxxxxxxxxxxxxx     xxxxxxxxx",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       x    v                 v                       v             x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx      x                                                            x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       x                                                            x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       x                                                            x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      x                                                            x",
   "x v            v                                x                                                            x",
   "x                                            xxxx                                                            x",
   "x                                                                                                            x",
   "x      o                                                     o                                   o           x",
   "x o                  o  =                             o                       o                            = x",
   "xxxx xxxxxx xxxxxx  xxxxxxxxx  xxxxxxxxxxxx  xxxxxxxxxxxxxx  xxxxxxxxxxx   xxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;

